### ISSUE TITLE
Playing the final card always causes an error

### ISSUE THREAD

**Issue by alaity47** [mkokotovich/play_smear#17]
This evening, every game ends with me trying to play the final card and getting a JSON error:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data.

I mean, I guess I could try doing something with my evening OTHER than playing your Smear game for a little while, but Katie's visiting in May and I've gotta up my game! ;P

**Comment by mkokotovich** [comment]
I think I found that coincidentally a few minutes ago, thanks for letting me know about it, though :)

Can you verify that it is working now?

**Comment by alaity47** [comment]
Yup, it seems to be fixed!  That's a pretty ace response time ;P

**Comment by mkokotovich** [comment]
What's funny is I had a test case for this, just forgot to run it before checking in. I think I'll need to hook up some sort of CI/CD pipeline to automatically run the tests :)

**Comment by alaity47** [comment]
I am literally in the middle of learning a whole 
github/Jenkins/Slack/Jira integration thing at work, so.... good luck 
with that!  ;P

**Comment by mkokotovich** [comment]
We use bitbucket, Jenkins, jira, and slack at work as well. I've seen people use TravisCI on GitHub, I think it's free. Might give it a try.
