### ISSUE TITLE
Can't use a name that a computer player might use

### ISSUE THREAD

**Issue by alaity47** [mkokotovich/play_smear#18]
A friend of mine created a game using the name 'Alex' - but 'Alex' is also one of the possible computer names.  You wind up with the game getting partially created (you can see the player names: Alex, Alex, Maisy, etc across the top) and then the error:

Unable to retrieve cardsSyntaxError: JSON Parse error:
Unrecognized token '<'

**Comment by mkokotovich** [comment]
Good catch. I'll fix this.

**Comment by mkokotovich** [comment]
The fix is live! Thanks again for letting me know about it.

Also, if you have more ideas for computer names, send them to me. Those were what Tim came up with :)
